site_name: SOMA Curation
site_description: Tools for managing and curating single-cell RNA sequencing data using TileDB-SOMA
site_url: https://phenomicai.github.io/soma-curation
repo_url: https://github.com/PhenomicAI/soma-curation
repo_name: PhenomicAI/soma-curation

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - navigation.instant
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - header.autohide
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: true
            heading_level: 2
  - mkdocs-jupyter:
      execute: false
  - git-revision-date-localized:
      enable_creation_date: true
  - mike:
      version_selector: true
      css_dir: css
      javascript_dir: js
      canonical_version: latest

extra:
  version:
    provider: mike
    default: latest
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/PhenomicAI/soma-curation
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/soma-curation

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - attr_list
  - md_in_html
  - def_list
  - toc:
      permalink: true

nav:
  - Getting Started:
      - Installation: getting_started/installation.md
      - Quick Start: getting_started/quickstart.md
      - Basic Concepts: getting_started/concepts.md
      - Releases & Versioning: getting_started/releases.md
  - Usage:
      - Basics: usage/basics.py
      - Data Organization: usage/data_organization.md
      - Appending to an Atlas: usage/append_atlas.md
  - Advanced:
      - Multiprocessing Ingestion: advanced/multiprocessing.md
  - API Reference:
      - Atlas: api_reference/atlas.md
      - Dataset: api_reference/dataset.md
