site_name: Data Curation
theme:
  name: material
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
  - mkdocs-jupyter:
      execute: false
nav:
  - Home: index.md
  - Usage:
      - Getting Started: usage/basics.py
  - API Reference:
      - Atlas: api_reference/atlas.md
      - Dataset: api_reference/dataset.md
