name: Documentation

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed
    branches:
      - main
  release:
    types: [published]

permissions:
  contents: write

jobs:
  deploy_docs:
    name: Deploy Docs
    if: |
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') ||
      (github.event_name == 'release')
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -e ".[docs]"

      - name: Setup Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Deploy Documentation (Main Branch)
        if: github.event_name == 'workflow_run'
        run: |
          mike deploy --push --update-aliases dev

      - name: Deploy Documentation (Release)
        if: github.event_name == 'release'
        run: |
          # Extract version from release tag
          VERSION=${GITHUB_REF#refs/tags/}

          # For pre-releases, just deploy as the version
          if [[ "${{ github.event.release.prerelease }}" == "true" ]]; then
            mike deploy --push $VERSION
          # For stable releases, deploy as the version and set as latest
          else
            mike deploy --push --update-aliases $VERSION latest
          fi
