name: Publish

on:
  release:
    types: [published]

permissions:
  contents: write
  id-token: write

jobs:
  build_release:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: python -m pip install build

      - name: Build distribution
        run: python -m build

      - name: Upload distribution
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifacts
          path: dist/

  publish_testpypi:
    name: Publish to TestPyPI
    needs: [build_release]
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/project/soma-curation/
    permissions:
      id-token: write
    if: github.event.release.prerelease == true
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-artifacts
          path: dist/

      - name: Publish to TestPyPI (trusted publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  publish_pypi:
    name: Publish to PyPI
    needs: [build_release]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/soma-curation/
    permissions:
      id-token: write
    if: github.event.release.prerelease == false
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-artifacts
          path: dist/

      - name: Publish to PyPI (trusted publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
